// Generated by scripts/prepare-portfolio.mjs — do not edit by hand.
export type MediaImage = { src: string; width: number; height: number; srcSet: string };

export const PORTFOLIO_MEDIA = {
  'project-solis': {
    src: '/media/portfolio/project-solis-1512.webp',
    width: 1512,
    height: 1008,
    srcSet: '/media/portfolio/project-solis-640.webp 640w, /media/portfolio/project-solis-960.webp 960w, /media/portfolio/project-solis-1280.webp 1280w, /media/portfolio/project-solis-1512.webp 1512w'
  },
  'watertown-factory': {
    src: '/media/portfolio/watertown-factory-1412.webp',
    width: 1412,
    height: 941,
    srcSet: '/media/portfolio/watertown-factory-640.webp 640w, /media/portfolio/watertown-factory-960.webp 960w, /media/portfolio/watertown-factory-1280.webp 1280w, /media/portfolio/watertown-factory-1412.webp 1412w'
  },
  'river-drivers-solar': {
    src: '/media/portfolio/river-drivers-solar-1403.webp',
    width: 1403,
    height: 935,
    srcSet: '/media/portfolio/river-drivers-solar-640.webp 640w, /media/portfolio/river-drivers-solar-960.webp 960w, /media/portfolio/river-drivers-solar-1280.webp 1280w, /media/portfolio/river-drivers-solar-1403.webp 1403w'
  },
  'new-mexico-panel-recycling': {
    src: '/media/portfolio/new-mexico-panel-recycling-1403.webp',
    width: 1403,
    height: 935,
    srcSet: '/media/portfolio/new-mexico-panel-recycling-640.webp 640w, /media/portfolio/new-mexico-panel-recycling-960.webp 960w, /media/portfolio/new-mexico-panel-recycling-1280.webp 1280w, /media/portfolio/new-mexico-panel-recycling-1403.webp 1403w'
  },
  'northern-maine-data-center': {
    src: '/media/portfolio/northern-maine-data-center-1412.webp',
    width: 1412,
    height: 941,
    srcSet: '/media/portfolio/northern-maine-data-center-640.webp 640w, /media/portfolio/northern-maine-data-center-960.webp 960w, /media/portfolio/northern-maine-data-center-1280.webp 1280w, /media/portfolio/northern-maine-data-center-1412.webp 1412w'
  },
  'integrated-energy-infrastructure': {
    src: '/media/portfolio/integrated-energy-infrastructure-1100.webp',
    width: 1100,
    height: 880,
    srcSet: '/media/portfolio/integrated-energy-infrastructure-640.webp 640w, /media/portfolio/integrated-energy-infrastructure-900.webp 900w, /media/portfolio/integrated-energy-infrastructure-1100.webp 1100w'
  }
} as const satisfies Record<string, MediaImage>;

export type MediaId = keyof typeof PORTFOLIO_MEDIA;
